In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/world_cup_2026_defensive_actions_raw.csv")

df.head()

,Rk,Player,Pos,Squad,Age,Born,90s,Tkl,TklW,Def 3rd,...,Lost,Blocks,Sh,Pass,Int,Tkl+Int,Clr,Err,Matches,-9999
0,1,Brenden Aaronson,MF,us USA,25,2000,0.8,NaN,1,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,Matches,5bc43860
1,2,Thelo Aasgaard,MF,no Norway,24,2002,1.0,NaN,1,NaN,...,NaN,NaN,NaN,NaN,3,NaN,NaN,NaN,Matches,c88a28b9
2,3,Hamza Abdelkarim,FW,eg Egypt,18,2008,0.7,NaN,0,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,Matches,057d8f12
3,4,Hossam Abdelmaguid,DF,eg Egypt,25,2001,0.7,NaN,0,NaN,...,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,Matches,accbfc94
4,5,Mohamed Abdelmonem,DF,eg Egypt,27,1999,0.2,NaN,0,NaN,...,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,Matches,bff15d74

In [2]:
print("Dataset size:", df.shape)
print(df.columns.tolist())
df.info()

Dataset size: (1039, 25)
['Rk', 'Player', 'Pos', 'Squad', 'Age', 'Born', '90s', 'Tkl', 'TklW', 'Def 3rd', 'Mid 3rd', 'Att 3rd', 'Tkl.1', 'Att', 'Tkl%', 'Lost', 'Blocks', 'Sh', 'Pass', 'Int', 'Tkl+Int', 'Clr', 'Err', 'Matches', '-9999']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1039 entries, 0 to 1038
Data columns (total 25 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Rk       1039 non-null   int64
 1   Player   1039 non-null   object
 2   Pos      1039 non-null   object
 3   Squad    1039 non-null   object
 4   Age      1039 non-null   int64
 5   Born     1039 non-null   int64
 6   90s      1039 non-null   float64
 7   Tkl      0 non-null      float64
 8   TklW     1039 non-null   int64
 9   Def 3rd  0 non-null      float64
 10  Mid 3rd  0 non-null      float64
 11  Att 3rd  0 non-null      float64
 12  Tkl.1    0 non-null      float64
 13  Att      0 non-null      float64
 14  Tkl%     0 non-null      float64
 15  Lost     0 non-null      float64
 16  Blocks   0 non-null      float64
 17  Sh       0 non-null      float64
 18  Pass     0 non-null      float64
 19  Int      1039 non-null   int64
 20  Tkl+Int  0 non-null      float64
 21  Clr      0 non-null      float64
 22  Err      0 non-null      float64
 23  Matches  1039 non-null   object
 24  -9999    1039 non-null   object
dtypes: float64(15), int64(5), object(5)
memory usage: 203.1+ KB

In [3]:
print("Total Rows and columns:", df.shape)

Total Rows and columns: (1039, 25)

In [4]:
analysis_df = df[["Player", "Pos", "Squad", "90s", "Int"]].copy()

analysis_df.head()

               Player Pos      Squad  90s  Int
0    Brenden Aaronson  MF     us USA  0.8    0
1      Thelo Aasgaard  MF  no Norway  1.0    3
2    Hamza Abdelkarim  FW   eg Egypt  0.7    0
3  Hossam Abdelmaguid  DF   eg Egypt  0.7    1
4  Mohamed Abdelmonem  DF   eg Egypt  0.2    0

In [5]:
analysis_df.isnull().sum()

Player    0
Pos       0
Squad     0
90s       0
Int       0
dtype: int64

## Data Cleaning and Eligibility

Players who were designated as either a defender (DF) or midfielder (MF) only, as well as players who have played for a minimum of 90 minutes, were chosen.

In [6]:
# Convert required columns to numbers
analysis_df["90s"] = pd.to_numeric(analysis_df["90s"], errors="coerce")
analysis_df["Int"] = pd.to_numeric(analysis_df["Int"], errors="coerce")

# Keep only eligible defenders and midfielders
eligible_df = analysis_df[
    (analysis_df["Pos"].isin(["DF", "MF"])) &
    (analysis_df["90s"] >= 1.0) &
    (analysis_df["Int"].notna())
].copy()

print(eligible_df["Pos"].value_counts())

Pos
MF    254
DF    253
Name: count, dtype: int64